name: TLS Handshake Modifier
dbless_compatible: 'yes'
free: No
plus: No
enterprise: Yes
konnect: No
network_config_opts: Self-managed traditional, DB-less, and hybrid
notes: --
categories:
  - security
