name: Proxy Caching Advanced
dbless_compatible: 'yes'
extra: |

  <div class="alert alert-ee red">
  <strong>Warning:</strong> The <code>content_type</code> parameter requires
  an exact match. For example, if your Upstream expects
  <code>application/json; charset=utf-8</code> and the
  <code>config.content_type</code> value is only <code>application/json</code>
  (a partial match), then the proxy cache is bypassed.
  </div>
free: false
plus: true
enterprise: true
konnect: true
network_config_opts: All
notes: --
categories:
  - traffic-control
publisher: Kong Inc.
desc: Cache and serve commonly requested responses in Kong
description: |
  This plugin provides a reverse proxy cache implementation for Kong. It caches
  response entities based on configurable response code and content type, as well
  as request method. It can cache per-Consumer or per-API. Cache entities are stored
  for a configurable period of time, after which subsequent requests to the same
  resource will re-fetch and re-store the resource. Cache entities can also be
  forcefully purged via the Admin API prior to their expiration time.
kong_version_compatibility:
  community_edition:
    compatible: null
  enterprise_edition:
    compatible: true
