name: Proxy Caching Advanced
dbless_compatible: 'yes'
extra: |

  <div class="alert alert-ee red">
  <strong>Warning:</strong> The <code>content_type</code> parameter requires
  an exact match. For example, if your Upstream expects
  <code>application/json; charset=utf-8</code> and the
  <code>config.content_type</code> value is only <code>application/json</code>
  (a partial match), then the proxy cache is bypassed.
  </div>
free: No
plus: Yes
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - traffic-control
