name: Azure Functions
dbless_compatible: 'yes'
extra: |
  Note: If `config.https_verify` is set as `true`, then the server certificate
  is verified according to the CA certificates specified by the
  `lua_ssl_trusted_certificate` directive in your Kong configuration.
free: Yes
plus: Yes
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - serverless
