name: azure-functions
service_id: true
route_id: true
consumer_id: true
protocols:
  - name: http
  - name: https
  - name: grpc
  - name: grpcs
  - name: tcp
  - name: tls
  - name: tls_passthrough
    minimum_version: "2.7.x"
  - name: udp
  - name: ws
    minimum_version: "3.0.x"
  - name: wss
    minimum_version: "3.0.x"
dbless_compatible: 'yes'
config:
  - name: functionname
    required: true
    default: null
    value_in_examples: <AZURE_FUNCTIONNAME>
    datatype: string
    description: Name of the Azure function to invoke.
  - name: appname
    required: true
    default: null
    value_in_examples: <AZURE_APPNAME>
    datatype: string
    description: The Azure app name.
  - name: hostdomain
    required: true
    default: azurewebsites.net
    value_in_examples: azurewebsites.net
    datatype: string
    description: The domain where the function resides.
  - name: routeprefix
    required: false
    default: /api
    value_in_examples: null
    datatype: string
    description: Route prefix to use.
  - name: apikey
    required: false
    default: null
    value_in_examples: <AZURE_APIKEY>
    datatype: string
    encrypted: true
    referenceable: true
    description: |
      The apikey to access the Azure resources. If provided, it is injected as the `x-functions-key` header.
  - name: clientid
    required: false
    default: null
    value_in_examples: null
    datatype: string
    encrypted: true
    referenceable: true
    description: |
      The `clientid` to access the Azure resources. If provided, it is injected as the `x-functions-clientid` header.
  - name: https_verify
    required: false
    default: false
    value_in_examples: null
    datatype: boolean
    description: Set to `true` to authenticate the Azure Functions server.
  - name: https
    required: false
    default: true
    value_in_examples: null
    datatype: boolean
    description: Use of HTTPS to connect with the Azure Functions server.
  - name: timeout
    required: false
    default: 600000
    value_in_examples: null
    datatype: number
    description: Timeout in milliseconds before closing a connection to the Azure Functions server.
  - name: keepalive
    required: false
    default: 60000
    value_in_examples: null
    datatype: number
    description: Time in milliseconds during which an idle connection to the Azure Functions server lives before being closed.
extra: |
  Note: If `config.https_verify` is set as `true`, then the server certificate
  is verified according to the CA certificates specified by the
  `lua_ssl_trusted_certificate` directive in your Kong configuration.
