name: forward-proxy
service_id: true
route_id: true
consumer_id: true
dbless_compatible: 'yes'
protocols:
  - name: http
  - name: https
  - name: grpc
  - name: grpcs
config:
  - name: http_proxy_host
    minimum_version: "2.8.x"
    required: semi
    default: null
    value_in_examples: example.com
    datatype: string
    description: |
      The HTTP hostname or IP address of the forward proxy to which to connect.
      Required if `http_proxy_port` is set.


      At least one of `http_proxy_host` or `https_proxy_host` must be specified.

      If `http_proxy_host` isn't set, the plugin falls back to the value
      configured in `https_proxy_host`.
  - name: http_proxy_port
    minimum_version: "2.8.x"
    required: semi
    default: null
    value_in_examples: 80
    datatype: string
    description: |
      The TCP port of the HTTP forward proxy to which to connect.
      Required if `http_proxy_host` is set.

      At least one of `http_proxy_port` or `https_proxy_port` must be specified.

      If `http_proxy_port` isn't set, the plugin falls back to the value
      configured in `https_proxy_port`.
  - name: https_proxy_host
    minimum_version: "2.8.x"
    required: semi
    default: null
    value_in_examples:
    datatype: string
    description: |
      The HTTPS hostname or IP address of the forward proxy to which to connect.
      Required if `https_proxy_port` is set.

      At least one of `http_proxy_host` or `https_proxy_host` must be specified.

      If `https_proxy_host` isn't set, the plugin falls back to the value
      configured in `http_proxy_host`.
  - name: https_proxy_port
    minimum_version: "2.8.x"
    required: semi
    default: null
    value_in_examples:
    datatype: string
    description: |
      The TCP port of the HTTPS forward proxy to which to connect.
      Required if `https_proxy_host` is set.

      At least one of `http_proxy_port` or `https_proxy_port` must be specified.

      If `https_proxy_port` isn't set, the plugin falls back to the value
      configured in `http_proxy_port`.
  - name: proxy_host
    maximum_version: "2.8.x"
    required: false
    default: null
    value_in_examples:
    datatype: string
    description: |

      {:.important}
      > This parameter is deprecated as of Kong Gateway 2.8.0.0 and
      is planned to be removed in a future release.
      > <br>
      > Use `http_proxy_host` or `https_proxy_host` instead.

      The hostname or IP address of the forward proxy to which to connect.
  - name: proxy_port
    maximum_version: "2.8.x"
    required: false
    default: null
    value_in_examples:
    datatype: string
    description: |

      {:.important}
      > This parameter is deprecated as of Kong Gateway 2.8.0.0 and
      is planned to be removed in a future release.
      > <br>
      > Use `http_proxy_host` or `https_proxy_host` instead.

      The TCP port of the forward proxy to which to connect.
  - name: proxy_scheme
    required: false
    default: http
    value_in_examples: http
    datatype: string
    description: |
      The proxy scheme to use when connecting. Only `http` is supported.
  - name: auth_username
    minimum_version: "2.7.x"
    required: false
    default: null
    value_in_examples: example_user
    datatype: string
    referenceable: true
    description: |
      The username to authenticate with, if the forward proxy is protected
      by basic authentication.
  - name: auth_password
    minimum_version: "2.7.x"
    required: false
    default: null
    value_in_examples: example_pass
    datatype: string
    referenceable: true
    description: |
      The password to authenticate with, if the forward proxy is protected
      by basic authentication.
  - name: https_verify
    required: false
    default: false
    value_in_examples: false
    datatype: boolean
    description: |
      Whether the server certificate will be verified according to the CA certificates
      specified in
      [lua_ssl_trusted_certificate](https://www.nginx.com/resources/wiki/modules/lua/#lua-ssl-trusted-certificate).
  - name: x_headers
    required: false
    default: append
    value_in_examples: transparent
    datatype: string
    description: |
      How the plugin handles the following headers:
      `X-Real-IP`, `X-Forwarded-For`, `X-Forwarded-Proto`, `X-Forwarded-Host`, and `X-Forwarded-Port`.

      The field should be set to one of the following values:
        - `append`: Append information from this hop to the headers.
        - `transparent`: Leave headers unchanged, as if not using a proxy.
        - `delete`: Remove all headers including those that should be added for this hop, as if you are the originating client.

      All options respect the trusted IP setting and will ignore last hop headers if they are not from clients with trusted IPs.

extra: |

  The plugin attempts to transparently replace upstream connections made by Kong
  core, sending the request instead to an intermediary forward proxy. Only
  transparent HTTP proxies are supported; TLS connections (via `CONNECT`)
  are not supported.
