name: Forward Proxy Advanced
dbless_compatible: 'yes'
extra: |

  The plugin attempts to transparently replace upstream connections made by Kong
  core, sending the request instead to an intermediary forward proxy. Only
  transparent HTTP proxies are supported; TLS connections (via `CONNECT`)
  are not supported.
free: No
plus: No
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - traffic-control
