apiVersion: v1
kind: Service
metadata:
  labels:
    app: tlsecho
  name: tlsecho
spec:
  ports:
    - port: 1030
      name: tls
      protocol: TCP
      targetPort: 1030
  selector:
    app: tlsecho
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tlsecho
  name: tlsecho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tlsecho
  strategy: {}
  template:
    metadata:
      labels:
        app: tlsecho
    spec:
      containers:
        - image: kong/go-echo:latest
          name: tlsecho
          ports:
            - containerPort: 1030 # TLS
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: TLS_PORT
              value: "1030"
            - name: TLS_CERT_FILE
              value: /var/run/certs/tls.crt
            - name: TLS_KEY_FILE
              value: /var/run/certs/tls.key
          volumeMounts:
            - mountPath: /var/run/certs
              name: secret-test
              readOnly: true
          resources: {}
      volumes:
        - name: secret-test
          secret:
            defaultMode: 420
            secretName: demo.example.com
