name: Rate Limiting Advanced
dbless_compatible: partially
dbless_explanation: |
  The cluster strategy is not supported in DB-less and hybrid modes. For Kong
  Gateway in DB-less or hybrid mode, the `redis` strategy is the only available option to configure the plugin with a central data store.

  {:.note}
  > **Note**: We recommend setting `namespace` to a static value in DB-less mode.
  > The `namespace` will be regenerated on every configuration change if not explicitly set, resetting counters to zero.
free: No
plus: No
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: |
  In Konnect, DB-less, and hybrid modes, the <code>cluster</code> config strategy
  is not supported.
  <br><br>
  For DB-less mode, use one of <code>redis</code> or <code>local</code>;
  for Konnect and hybrid mode, use <code>redis</code>, or <code>local</code> for data
  planes only.
categories:
  - traffic-control
