name: tcp-log
service_id: true
route_id: true
consumer_id: true
protocols:
  - name: http
  - name: https
  - name: tcp
  - name: tls
  - name: tls_passthrough
    minimum_version: "2.7.x"
  - name: udp
  - name: grpc
  - name: grpcs
  - name: ws
    minimum_version: "3.1.x"
  - name: wss
    minimum_version: "3.1.x"
dbless_compatible: 'yes'
config:
  - name: host
    required: true
    value_in_examples: 127.0.0.1
    datatype: string
    description: The IP address or host name to send data to.
  - name: port
    required: true
    value_in_examples: 9999
    datatype: integer
    description: The port to send data to on the upstream server.
  - name: timeout
    required: false
    default: '`10000`'
    datatype: number
    description: An optional timeout in milliseconds when sending data to the upstream server.
  - name: keepalive
    required: false
    default: '`60000`'
    datatype: number
    description: An optional value in milliseconds that defines how long an idle connection lives before being closed.
  - name: tls
    required: true
    default: false
    datatype: boolean
    description: Indicates whether to perform a TLS handshake against the remote server.
  - name: tls_sni
    required: false
    default: null
    datatype: string
    description: An optional string that defines the SNI (Server Name Indication) hostname to send in the TLS handshake.
  - name: custom_fields_by_lua
    minimum_version: "2.4.x"
    required: false
    default: null
    datatype: map
    description: |
      A list of key-value pairs, where the key is the name of a log field and
      the value is a chunk of Lua code, whose return value sets or replaces
      the log field value.
