name: TCP Log
dbless_compatible: 'yes'
free: true
plus: true
enterprise: true
konnect: true
network_config_opts: All
notes: --
categories:
  - logging
publisher: Kong Inc.
desc: Send request and response logs to a TCP server
description: |
  Log request and response data to a TCP server.
kong_version_compatibility:
  community_edition:
    compatible: true
  enterprise_edition:
    compatible: true
