name: GraphQL Rate Limiting Advanced
konnect_examples: false
dbless_compatible: partially
dbless_explanation: |
  The cluster strategy is not supported in DB-less and hybrid modes. For Kong
  Gateway in DB-less or hybrid mode, use the `redis` strategy.
free: No
plus: No
enterprise: Yes
konnect: No
network_config_opts: Self-managed traditional, DB-less, and hybrid
notes: |
  In DB-less and hybrid modes, the <code>cluster</code> config strategy
  is not supported. Use <code>redis</code> instead.
categories:
  - traffic-control
