name: Request Transformer Advanced
konnect_examples: false
dbless_compatible: 'yes'
extra: |
  **Notes:**
  * If the value contains a `,` (comma), then the comma-separated format for lists cannot be used. The array
  notation must be used instead.
  * The `X-Forwarded-*` fields are non-standard header fields written by Nginx to inform the upstream about client details and can't be overwritten by this plugin. If you need to overwrite these header fields, see the [post-function plugin in Serverless Functions](https://docs.konghq.com/hub/kong-inc/serverless-functions/).
free: No
plus: No
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - transformations
