- match:
    version: "3\\..*"
    package:
      - oss
      - enterprise
  distros:
    - amazon-linux
  arch:
    - linux/amd64
  outputs:
    oss: "{{ version }}"
    enterprise: "Kong Enterprise {{ version }}"

- match:
    version: "3\\..*"
    package:
      - enterprise
  distros:
    - amazon-linux
  arch:
    - linux/arm64
  skip:
    - 3.0.x/amazon-linux/enterprise/package
    - 3.0.x/amazon-linux/enterprise/repository
    - 3.1.x/amazon-linux/enterprise/package
    - 3.1.x/amazon-linux/enterprise/repository
  outputs:
    enterprise: "Kong Enterprise {{ version }}"

- match:
    version: "3\\..*"
    package:
      - oss
      - enterprise
  distros:
    - ubuntu
    - rhel
    - debian
  arch:
    - linux/amd64
  outputs:
    enterprise: "Kong Enterprise {{ version }}"
    oss: "{{ version }}"
- match:
    version: "2\\..*"
    package:
      - oss
      - enterprise
  distros:
    - ubuntu
    - rhel
    - amazon-linux
    - debian
    - centos
  arch:
    - linux/amd64
  skip:
    - 2.8.x/centos/oss/package # No OSS package for 2.8
    - 2.8.x/centos/oss/repository # No OSS package for 2.8
  outputs:
    enterprise: "Kong Enterprise {{ version }}"
    oss: "{{ version }}"
