name: Kong JWT Signer
dbless_compatible: 'yes'
extra: |
  **Configuration Notes:**

  Most of the parameters are optional, but you need to specify some options to actually
  make the plugin work:

  * For example, signature verification cannot be done without the plugin knowing about
  `config.access_token_jwks_uri` and/or `config.channel_token_jwks_uri`.

  * Also for introspection to work, you need to specify introspection endpoints
  `config.access_token_introspection_endpoint` and/or `config.channel_token_introspection_endpoint`.
free: No
plus: Yes
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - authentication
