name: Kong Response Size Limiting
api_id: false
service_id: true
route_id: true
consumer_id: true
dbless_compatible: yes
config:
  - name: allowed_payload_size
    required: true
    default: "`128`"
    value_in_examples: 128
    description: Allowed upstream response payload size in megabytes, default is `128` (128000000 Bytes)
publisher: Optum

desc: Block responses with bodies greater than a specified size
description: |

  Block upstream responses whose body is greater than a specific size in megabytes.

  Proxy consumers will receive an HTTP Status of 413 and message body "Response size limit exceeded" in the event the body is greater than configured size.

categories:
  - traffic-control

support_url: https://github.com/Optum/kong-response-size-limiting/issues

source_code: https://github.com/Optum/kong-response-size-limiting/

license_type: Apache-2.0

kong_version_compatibility:
  community_edition:
    compatible:
      - 0.14.x

  enterprise_edition:
    compatible:
      - 0.34-x
