name: Prometheus
dbless_compatible: 'yes'
dbless_explanation: |
  The database will always be reported as reachable in Prometheus with DB-less.
  Additionally, the DB entity count metric (`kong_db_entities_total`) is not
  emitted in DB-less mode.
free: true
plus: true
enterprise: true
konnect: true
network_config_opts: All
notes: --
categories:
  - analytics-monitoring
publisher: Kong Inc.
desc: Expose metrics related to Kong and proxied upstream services in Prometheus exposition format