strategy: gateway
delegate_releases: true
releases:
  - 3.0.x
  - 2.8.x
  - 2.7.x
  - 2.5.x
  - 2.0.x-CE
  - 1.5.x-EE
sources:
  2.0.x-CE: _0.8.x
  1.5.x-EE: _0.8.x
overrides:
  3.0.x: 3.0.x
  2.8.x: 1.6.x
  2.7.x: 1.4.x
  2.5.x: 1.3.x
  2.0.x-CE: 0.8.x
  1.5.x-EE: 0.8.x