name: Session
dbless_compatible: partially
dbless_explanation: |
  `config.storage` must be set to `cookie`. The `kong` strategy uses
  a database, and is not supported. The plugin currently lacks checks
  for this invalid configuration in DB-less mode.
free: Yes
plus: Yes
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - authentication
