name: application-registration
global: false
service_id: true
consumer_id: false
route_id: false
konnect_examples: false
protocols:
  - name: http
  - name: https
  - name: grpc
  - name: grpcs
dbless_compatible: 'no'
config:
  - name: auto_approve
    required: true
    default: '`false`'
    value_in_examples: false
    datatype: boolean
    description: |
      If enabled, all new Service Contracts requests are automatically
      approved. See [Enable automatic registration approval](#enable-automatic-registration-approval). Otherwise, Dev Portal admins must manually approve requests.
  - name: description
    required: false
    default: null
    value_in_examples: <my_service_description>
    datatype: string
    description: |
      Unique description displayed in information about a Service in the Developer Portal.
  - name: display_name
    required: true
    default: null
    value_in_examples: <my_service_display_name>
    datatype: string
    description: |
      Unique display name used for a Service in the Developer Portal.
  - name: show_issuer
    required: true
    default: '`false`'
    value_in_examples: false
    datatype: boolean
    description: |
      Displays the **Issuer URL** in the **Service Details** dialog.
