name: gRPC-gateway
dbless_compatible: 'yes'
free: true
plus: true
enterprise: true
konnect: true
network_config_opts: All
notes: --
categories:
  - transformations
publisher: Kong Inc.
desc: Access gRPC services through HTTP REST
description: |
  A Kong plugin to allow access to a gRPC service via HTTP REST requests
  and translate requests and responses in a JSON format. Similar to
  [gRPC-gateway](https://grpc-ecosystem.github.io/grpc-gateway/).
license_type: MIT
kong_version_compatibility:
  community_edition:
    compatible: true
  enterprise_edition:
    compatible: true
