apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: accessrolebindings.kuma.io
spec:
  group: kuma.io
  names:
    kind: AccessRoleBinding
    plural: accessrolebindings
  scope: Cluster
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: AccessRoleBinding is the Schema for the accessrolebinding API
          properties:
            mesh:
              type: string
            spec:
              x-kubernetes-preserve-unknown-fields: true
              type: object
          type: object
