name: jq
yaml_examples: false
konnect_examples: false
dbless_compatible: null
examples: false
free: No
plus: No
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - transformations
