name: Apache OpenWhisk
konnect_examples: false
dbless_compatible: 'yes'
extra: |
  Note: If `config.https_verify` is set to `true`, then the server certificate
  is verified according to the CA certificates specified by the
  `lua_ssl_trusted_certificate` directive in your Kong configuration.
free: Yes
plus: Yes
enterprise: Yes
konnect: No
network_config_opts: Self-managed traditional, DB-less, and hybrid
notes: |
  Not bundled with Kong Gateway.
  <br><br>
  Installed as a LuaRocks package.
categories:
  - serverless
