extends: spelling
message: "Did you really mean '%s'?"
level: error
scope: raw
filters:
  - '\W'
ignore: 
 - .github/styles/kongplugins/dictionary.txt
 - .github/styles/kongplugins/auto-ignore.txt
 - .github/styles/kongplugins/plugin-ignore.txt