params:
  name: kafka-log
  dbless_compatible: 'yes'
  protocols:
    - name: http
    - name: https
    - name: grpc
    - name: grpcs
    - name: ws
      minimum_version: "3.1.x"
    - name: wss
      minimum_version: "3.1.x"
  config:
    - name: bootstrap_servers
      required: true
      value_in_examples:
        BOOTSTRAP_SERVERS: null
      urlencode_in_examples: true
      default: null
      datatype: set of record elements
      description: |
        Set of bootstrap brokers in a `{host: host, port: port}` list format.
    - name: topic
      required: true
      value_in_examples:
        TOPIC: null
      urlencode_in_examples: true
      default: null
      datatype: string
      description: |
        The Kafka topic to publish to.
    - name: authentication.strategy
      minimum_version: "2.6.x"
      required: false
      value_in_examples: sasl
      urlencode_in_examples: true
      default: null
      datatype: string
      description: |
        The authentication strategy for the plugin, the only option for the value is `sasl`.

    - name: authentication.mechanism # Old version of parameter
      minimum_version: "2.6.x"
      maximum_version: "2.7.x"
      required: false
      value_in_examples: PLAIN
      urlencode_in_examples: true
      default: null
      datatype: string
      description: |
        The SASL authentication mechanism.

        Supported options: `PLAIN` or `SCRAM-SHA-256`.

    - name: authentication.mechanism # Current version of parameter
      minimum_version: "2.8.x"
      required: false
      value_in_examples: PLAIN
      urlencode_in_examples: true
      default: null
      datatype: string
      description: |
        The SASL authentication mechanism.

        Supported options: `PLAIN`, `SCRAM-SHA-256`, or `SCRAM-SHA-512`.

    - name: authentication.user
      minimum_version: "2.6.x"
      required: false
      value_in_examples: admin
      urlencode_in_examples: true
      default: null
      datatype: string
      encrypted: true
      referenceable: true
      description: |
        Username for SASL authentication.
    - name: authentication.password
      minimum_version: "2.6.x"
      required: false
      value_in_examples: admin-secret
      urlencode_in_examples: true
      default: null
      datatype: string
      encrypted: true
      referenceable: true
      description: |
        Password for SASL authentication.
    - name: authentication.tokenauth
      minimum_version: "2.6.x"
      required: false
      value_in_examples: false
      default: false
      datatype: boolean
      description: |
        Enable this to indicate `DelegationToken` authentication
    - name: security.ssl
      minimum_version: "2.6.x"
      required: false
      value_in_examples: false
      default: false
      datatype: boolean
      description: |
        Enables TLS.
    - name: security.certificate_id
      minimum_version: "2.6.x"
      required: false
      urlencode_in_examples: true
      value_in_examples: nil
      default: null
      datatype: string
      description: |
        UUID of certificate entity for mTLS authentication.
    - name: timeout
      required: false
      default: '`10000`'
      value_in_examples: 10000
      datatype: integer
      description: |
        Socket timeout in milliseconds.
    - name: keepalive
      required: false
      default: '`60000`'
      value_in_examples: 60000
      datatype: integer
      description: |
        Keepalive timeout in milliseconds.
    - name: cluster_name
      minimum_version: "2.8.x"
      required: false
      default: '`<autogenerated-value>`'
      value_in_examples:
      datatype: string
      description: |
        An identifier for the Kafka cluster. By default, this field generates a
        random string. You can also set your own custom cluster identifier.

        If more than one Kafka plugin is configured without a `cluster_name`
        (that is, if the default autogenerated value is removed),
        these plugins will use the same producer, and by extension, the same
        cluster. Logs will be sent to the leader of the cluster.
    - name: producer_request_acks
      required: false
      default: '`1`'
      value_in_examples: -1
      datatype: integer
      description: |
        The number of acknowledgments the producer requires the leader to have received before
        considering a request complete. Allowed values: 0 for no acknowledgments; 1 for only the
        leader; and -1 for the full ISR (In-Sync Replica set).
    - name: producer_request_timeout
      required: false
      default: '`2000`'
      value_in_examples: 2000
      datatype: integer
      description: |
        Time to wait for a Produce response in milliseconds
    - name: producer_request_limits_messages_per_request
      required: false
      default: '`200`'
      value_in_examples: 200
      datatype: integer
      description: |
        Maximum number of messages to include into a single Produce request.
    - name: producer_request_limits_bytes_per_request
      required: false
      default: '`1048576`'
      value_in_examples: 1048576
      datatype: integer
      description: |
        Maximum size of a Produce request in bytes.
    - name: producer_request_retries_max_attempts
      required: false
      default: '`10`'
      value_in_examples: 10
      datatype: integer
      description: |
        Maximum number of retry attempts per single Produce request.
    - name: producer_request_retries_backoff_timeout
      required: false
      default: '`100`'
      datatype: integer
      description: |
        Backoff interval between retry attempts in milliseconds.
    - name: producer_async
      required: false
      default: '`true`'
      datatype: boolean
      description: |
        Flag to enable asynchronous mode.
    - name: producer_async_flush_timeout
      required: false
      default: '`1000`'
      datatype: integer
      description: |
        Maximum time interval in milliseconds between buffer flushes in asynchronous mode.
    - name: producer_async_buffering_limits_messages_in_memory
      required: false
      default: '`50000`'
      datatype: integer
      description: |
        Maximum number of messages that can be buffered in memory in asynchronous mode.
    - name: api_version
      maximum_version: "2.5.x"
      required: false
      default: "`0`"
      value_in_examples: 0
      datatype: integer
      description: |
        API version of a Produce request. Allowed values: `0`, `1`, or `2`.
