name: oas-validation
service_id: true
route_id: true
consumer_id: false
protocols:
  - name: http
  - name: https
dbless_compatible: 'yes'
konnect_examples: true
config:
  - name: api_spec
    required: true
    datatype: string
    value_in_examples: '{your API specification}'
    description: |
      The API specification defined using either Swagger or the OpenAPI. This can be either a JSON or YAML based file. If using a YAML file, the spec needs to be URL encoded to preserve the YAML format.
  - name: validate_request_uri_params
    required: false
    datatype: boolean
    default: true
    description: |
      If set to true, validates URI parameters in the request against the API specification.
  - name: validate_request_header_params
    required: false
    datatype: boolean
    default: true
    description: |
      If set to true, validates HTTP header parameters against the API specification.
  - name: validate_request_query_params
    required: false
    datatype: boolean
    default: true
    description: |
      If set to true, validates query parameters against the API specification.
  - name: validate_request_body
    required: false
    datatype: boolean
    default: true
    description: |
      If set to true, validates the request body content against the API specification.
  - name: notify_only_request_validation_failure
    required: false
    datatype: boolean
    default: false
    description: |
      If set to true, notifications via event hooks are enabled, but request based validation failures don't affect the request flow.
  - name: validate_response_body
    required: false
    datatype: boolean
    default: false
    description: |
      If set to true, validates the response from the upstream services against the API specification. If validation fails, it results in an `HTTP 406 Not Acceptable` status code.
  - name: notify_only_response_body_validation_failure
    required: false
    datatype: boolean
    default: false
    description: |
      If set to true, notifications via event hooks are enabled, but response validation failures don't affect the response flow.
  - name: header_parameter_check
    required: true
    datatype: boolean
    default: false
    description: |
      If set to true, checks if HTTP header parameters in the request exist in the API specification.
  - name: query_parameter_check
    required: true
    datatype: boolean
    default: false
    description: |
      If set to true, checks if query parameters in the request exist in the API specification.
  - name: allowed_header_parameters
    required: false
    datatype: string
    default: '`Host,Content-Type,User-Agent,Accept,Content-Length`'
    description: |
      List of header parameters in the request that will be ignored when performing HTTP header validation. These are additional headers added to an API request beyond those defined in the API specification.

      For example, you might include the HTTP header `User-Agent`, which lets servers and network peers identify the application, operating system, vendor, and/or version of the requesting user agent.
  - name: verbose_response
    required: false
    datatype: boolean
    default: false
    value_in_examples: true
    description: |
      If set to true, returns a detailed error message for invalid requests & responses. This is useful while testing.
