name: TLS Metadata Headers
dbless_compatible: 'yes'
extra: |

  The plugin must be used in conjunction with any plugin which requests a client certificate, such as
  the mTLS Authentication or TLS Handshake Modifier plugins.
free: No
plus: No
enterprise: Yes
konnect: No
network_config_opts: Self-managed traditional, DB-less, and hybrid
notes: --
categories:
  - security
