name: StatsD
dbless_compatible: 'yes'
extra: |
  By default, the plugin sends a packet for each metric it observes. The `udp_packet_size` option
  configures the greatest datagram size the plugin can combine. It should be less than
  65507 according to UDP protocol. Consider the MTU of the network when setting this parameter.
free: Yes
plus: Yes
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - logging
