name: HMAC Auth
dbless_compatible: partially
dbless_explanation: |
  Consumers and Credentials can be created with declarative configuration.

  Admin API endpoints that do POST, PUT, PATCH or DELETE on Credentials will not work on DB-less mode.
extra: |
  Once applied, any user with a valid credential can access the Service/Route.
  To restrict usage to only some of the authenticated users, also add the
  [ACL](/plugins/acl/) plugin (not covered here) and create allowed or
  denied groups of users.
free: Yes
plus: Yes
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - authentication
