params:
  name: hmac-auth
  service_id: true
  route_id: true
  consumer_id: false
  protocols:
    - name: http
    - name: https
    - name: grpc
    - name: grpcs
    - name: ws
      minimum_version: "3.0.x"
    - name: wss
      minimum_version: "3.0.x"
  dbless_compatible: partially
  dbless_explanation: |
    Consumers and Credentials can be created with declarative configuration.

    Admin API endpoints that do POST, PUT, PATCH or DELETE on Credentials will not work on DB-less mode.
  config:
    - name: hide_credentials
      required: true
      default: '`false`'
      datatype: boolean
      description: |
        An optional boolean value telling the plugin to show or hide the credential from the upstream service. If `true`, the plugin strips the credential from the request (i.e. the `Authorization` header) before proxying it.
    - name: clock_skew
      required: false
      default: '`300`'
      datatype: number
      description: |
        [Clock Skew](https://tools.ietf.org/html/draft-cavage-http-signatures-00#section-3.4) in seconds to prevent replay attacks.
    - name: anonymous
      required: false
      default: null
      datatype: string
      description:
        An optional string (Consumer UUID or username) value to use as an “anonymous” consumer if authentication fails. If empty (default null), the request will fail with an authentication failure `4xx`. Please note that this value must refer to the Consumer `id` or `username` attribute, and **not** its `custom_id`.
      minimum_version: "3.1.x"
    - name: anonymous
      required: false
      default: null
      datatype: string
      description: |
        An optional string (consumer UUID) value to use as an anonymous consumer if authentication fails.
        If empty (default), the request will fail with an authentication failure `4xx`. Note that this value
        must refer to the consumer `id` attribute that is internal to Kong Gateway, and **not** its `custom_id`.
      maximum_version: "3.0.x"
    - name: validate_request_body
      required: true
      default: '`false`'
      datatype: boolean
      description: A boolean value telling the plugin to enable body validation.
    - name: enforce_headers
      required: false
      default: null
      datatype: array of string elements
      description: A list of headers that the client should at least use for HTTP signature creation.
    - name: algorithms
      required: false
      default: '`hmac-sha1`,<br>`hmac-sha256`,<br>`hmac-sha384`,<br>`hmac-sha512`'
      datatype: array of string elements
      description: |
        A list of HMAC digest algorithms that the user wants to support. Allowed values are `hmac-sha1`, `hmac-sha256`, `hmac-sha384`, and `hmac-sha512`
  extra: |
    Once applied, any user with a valid credential can access the Service/Route.
    To restrict usage to only some of the authenticated users, also add the
    [ACL](/plugins/acl/) plugin (not covered here) and create allowed or
    denied groups of users.
