name: Mutual TLS Authentication
dbless_compatible: 'yes'
free: false
plus: true
enterprise: true
konnect: true
network_config_opts: All
notes: --
categories:
  - authentication
kong_version_compatibility:
  community_edition:
    compatible: null
  enterprise_edition:
    compatible: true
publisher: Kong Inc.
desc: Secure routes and services with client certificate and mutual TLS authentication
description: |
  Add mutual TLS authentication based on client-supplied or server-supplied certificate, and on the configured trusted CA list. Automatically maps certificates to consumers based on the common name field.
