params:
  name: acme
  service_id: false
  route_id: false
  consumer_id: false
  protocols:
    - name: http
    - name: https
    - name: grpc
    - name: grpcs
  dbless_compatible: 'yes'
  config:
    - name: account_email
      required: 'yes'
      default: null
      value_in_examples: example@example.com
      encrypted: true
      datatype: string
      referenceable: true
      description: |
        The account identifier. Can be reused in a different plugin instance.
    - name: api_uri
      required: false
      default: '` https://acme-v02.api.letsencrypt.org/directory`'
      datatype: string
      description: |
        The ACMEv2 API endpoint to use. You can specify the
        [Let's Encrypt staging environment](https://letsencrypt.org/docs/staging-environment/) for testing. Kong doesn't automatically delete staging certificates. If you use the same domain in test and production environments, you need to manually delete those certificates after testing.
    - name: cert_type
      required: false
      default: '`rsa`'
      datatype: string
      description: |
        The certificate type to create. The possible values are `"rsa"` for RSA certificate or `"ecc"` for EC certificate.
    - name: domains
      required: false
      default: '`[]`'
      datatype: array of string elements
      description: |
        The list of domains to create certificates for. To match subdomains under `example.com`, use `*.example.com`.
        Regex pattern is not supported.

        This parameter is only used to match domains, not to specify the Common Name
        or Subject Alternative Name to create certificates. Each domain must have its own certificate.
        The ACME plugin checks this configuration before checking any certificate in `storage` when serving the certificate of a request.

        If this field is left empty, all top-level domains (TLDs) are allowed.
    - name: allow_any_domain
      minimum_version: "3.0.x"
      required: false
      default: false
      datatype: boolean
      description: |
        If set to `true`, the plugin allows all domains and ignores any values in the `domains` list.
    - name: fail_backoff_minutes
      minimum_version: "2.1.x"
      required: false
      default: 5
      datatype: number
      description: |
        Minutes to wait for each domain that fails to create a certificate. This applies to both a
        new certificate and a renewal certificate.
    - name: renew_threshold_days
      required: false
      default: '`14`'
      datatype: number
      description: |
        Days remaining to renew the certificate before it expires.
    - name: storage
      required: false
      default: '`shm`'
      datatype: string
      description: |
        The backend storage type to use. The possible values are `"kong"`, `"shm"`, `"redis"`, `"consul"`, or `"vault"`. In DB-less mode, `"kong"` storage is unavailable. Note that `"shm"` storage does not persist during Kong restarts and does not work for Kong running on different machines, so consider using one of `"kong"`, `"redis"`, `"consul"`, or `"vault"` in production. Please refer to the Hybrid Mode sections below as well.
    - name: storage_config
      required: false
      default: null
      datatype: record
      description: |
        Storage configs for each backend storage. See [Storage configuration considerations](#storage-config)
        for information on its default values.
    - name: tos_accepted
      required: false
      default: '`false`'
      datatype: boolean
      description: |
        If you are using Let's Encrypt, you must set this to `true` to agree the [Terms of Service](https://letsencrypt.org/repository/).
    - name: eab_kid
      minimum_version: "2.4.x"
      required: false
      datatype: string
      encrypted: true
      referenceable: true
      description: |
        External account binding (EAB) key id. You usually don't need to set this unless it is explicitly required by the CA.
    - name: eab_hmac_key
      minimum_version: "2.4.x"
      required: false
      datatype: string
      encrypted: true
      referenceable: true
      description: |
        External account binding (EAB) base64-encoded URL string of the HMAC key. You usually don't need to set this unless it is explicitly required by the CA.
    - name: rsa_key_size
      minimum_version: "2.8.x"
      required: false
      datatype: number
      default: 4096
      description: |
        RSA private key size for the certificate. The possible values are 2048, 3072, or 4096.
