name: Key Auth
dbless_compatible: partially
dbless_explanation: |
  Consumers and Credentials can be created with declarative configuration.

  Admin API endpoints that do POST, PUT, PATCH, or DELETE on Credentials are not available on DB-less mode.
free: true
plus: true
enterprise: true
konnect: true
network_config_opts: All
notes: |
  The time-to-live (ttl) does not work in Konnect or hybrid mode. This setting
  determines the length of time a credential remains valid.
categories:
  - authentication
kong_version_compatibility:
  community_edition:
    compatible: true
  enterprise_edition:
    compatible: true
publisher: Kong Inc.
desc: Add key authentication to your Services
description: |
  Add key authentication (also sometimes referred to as an _API key_) to a service or a route.
  Consumers then add their API key either in a query string parameter, a header, or a
  request body to authenticate their requests.

  This plugin can be used for authentication in conjunction with the
  [Application Registration](/hub/kong-inc/application-registration/) plugin.

  **Tip:** The Kong Gateway [Key Authentication Encrypted](/hub/kong-inc/key-auth-enc/)
    plugin provides the ability to encrypt keys. Keys are encrypted at rest in the API gateway datastore.
