local data = {}

data.header = [[
---
#
#  WARNING: this file was auto-generated by a script.
#  DO NOT edit this file directly. Instead, send a pull request to change
#  the files in https://github.com/Kong/docs.konghq.com/tree/main/autodoc-conf-ee
#
title: Configuration Reference for Kong Gateway
source_url: https://github.com/Kong/kong-ee/blob/master/kong.conf.default
---

Reference for {{site.base_gateway}} configuration parameters. Set these parameters in `kong.conf`.

To learn more about the `kong.conf` file, see the guide on the [Kong Configuration File](/gateway/{{page.kong_version}}/kong-production/kong-conf).
]]


data.footer = [[


[Penlight]: http://stevedonovan.github.io/Penlight/api/index.html
[pl.template]: http://stevedonovan.github.io/Penlight/api/libraries/pl.template.html
[templates]: https://github.com/kong/kong/tree/master/kong/templates
]]

return data
