local data = {}

data.header = [[
---
#
# WARNING: this file was auto-generated by a script.
# DO NOT edit this file directly. Instead, send a pull 
# request to change the file at 
# https://github.com/Kong/kong/blob/master/kong.conf.default.

# If you can't find the parameter at the Kong/kong URL, the parameter 
# must be updated in Kong/kong-ee:
# https://github.com/Kong/kong-ee/blob/master/kong.conf.default

title: Configuration Reference for Kong Gateway
source_url: https://github.com/Kong/kong/blob/master/kong.conf.default
---

<!-- vale off -->

Reference for {{site.base_gateway}} configuration parameters. Set these parameters in `kong.conf`.

To learn more about the `kong.conf` file, see the guide on the [Kong Configuration File](/gateway/{{page.release}}/production/kong-conf).

]]


data.footer = [[


[Penlight]: http://stevedonovan.github.io/Penlight/api/index.html
[pl.template]: http://stevedonovan.github.io/Penlight/api/libraries/pl.template.html
[templates]: https://github.com/kong/kong/tree/master/kong/templates
]]

return data
