[build]
  publish = "dist"
  command = "bundle exec jekyll build --config jekyll.yml"
  environment = { JEKYLL_ENV = "development", BUNDLE_WITHOUT = "development", NODE_OPTIONS = "--max_old_space_size=8192" }

[context.main.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "preview"

[dev]
  autoLaunch = false
  framework = "#static"
