name: Exit Transformer
yaml_examples: false
konnect_examples: false
dbless_compatible: 'yes'
free: No
plus: Yes
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - transformations
