name: OAuth 2.0 Authentication
yaml_examples: false
konnect_examples: false
dbless_compatible: 'no'
dbless_explanation: |
  For its regular work, the plugin needs to both generate and delete tokens, and commit those changes to the database, which is not compatible with DB-less.

  In addition to this, its Admin API endpoints offer several POST, PATCH, PUT, and DELETE methods for tokens and credentials. None of them would work on DB-less.
extra: |

  Once applied, any user with a valid credential can access the Service.
  To restrict usage to only some of the authenticated users, also add the
  [ACL](/plugins/acl/) plugin (not covered here) and create allowed or
  denied groups of users.
free: Yes
plus: No
enterprise: Yes
konnect: No
network_config_opts: Self-managed traditional only
notes: |
  This plugin can't be used in Konnect, hybrid, or DB-less modes. It needs to
  generate and delete tokens, and commit those changes to a database on the
  same node.
categories:
  - authentication
