name: route-transformer-advanced
service_id: true
route_id: true
consumer_id: true
konnect_examples: false
dbless_compatible: 'yes'
protocols:
  - name: http
  - name: https
  - name: grpc
  - name: grpcs
config:
  - name: path
    required: semi
    value_in_examples:
      - /path
    datatype: string
    description: |
      Updates the upstream request path with given value/template. This value can only be used to update the path part of the URI, not the scheme, nor the hostname. One of `config.path` or `config.host` or `config.port` must be specified.
  - name: host
    required: semi
    datatype: string
    description: |
      Updates the upstream request Host with given value/template. This value can only be used to update the routing, it will not update the Host-header value. One of `config.path` or `config.host` or `config.port` must be specified.
  - name: port
    required: semi
    datatype: string
    description: |
      Updates the upstream request Port with given value/template. Note that the port as set may be overridden again by DNS resolution (in case of SRV records,or an Upstream) One of `config.path` or `config.host` or `config.port` must be specified.
  - name: escape_path
    required: false
    datatype: boolean
    default: false
    description: |
      If set to true, the path is escaped after being transformed.
    minimum_version: "3.1.x"
