name: Key Authentication - Encrypted
konnect_examples: false
dbless_compatible: partially
dbless_explanation: |
  Consumers and credentials can be created with declarative configuration.

  Admin API endpoints that do POST, PUT, PATCH, or DELETE on credentials are not available on DB-less mode.
free: No
plus: No
enterprise: Yes
konnect: No
network_config_opts: Self-managed traditional, DB-less, and hybrid
notes: |
  The time-to-live (ttl) does not work in Konnect or hybrid mode. This setting
  determines the length of time a credential remains valid.
categories:
  - authentication
