params:
  name: opa
  service_id: true
  route_id: true
  consumer_id: false
  protocols:
    - name: http
    - name: https
    - name: grpc
    - name: grpcs
  dbless_compatible: 'yes'
  config:
    - name: opa_protocol
      required: false
      datatype: string
      default: '`http`'
      description: |
        The protocol to use when talking to Open Policy Agent (OPA) server. Allowed protocols are `http` and `https`.
    - name: opa_host
      required: false
      value_in_examples: localhost
      datatype: string
      default: '`localhost`'
      description: |
        The DNS name or IP address of the OPA server.
    - name: opa_port
      required: false
      value_in_examples: 8181
      datatype: integer
      default: '`8181`'
      description: |
        The port of the OPA server.
    - name: opa_path
      required: true
      value_in_examples: </v1/data/example/kong/allowBoolean>
      datatype: string
      description: |
        The HTTP path to use when making a request to the OPA server. This is usually the path to the policy and rule to evaluate, prefixed with `/v1/data/`. For example,
        if you want to evaluate the `allow` rule inside `example.kong` package, then the path would be `/v1/data/example/kong/allowBoolean`.
    - name: include_service_in_opa_input
      required: false
      datatype: boolean
      default: false
      description: |
        If set to true, the Kong Gateway Service object in use for the current request is included as input to OPA.
    - name: include_route_in_opa_input
      required: false
      datatype: boolean
      default: false
      description: |
        If set to true, the Kong Gateway Route object in use for the current request is included as input to OPA.
    - name: include_consumer_in_opa_input
      required: false
      datatype: boolean
      default: false
      description: |
        If set to true, the Kong Gateway Consumer object in use for the current request (if any) is included as input to OPA.
    - name: include_body_in_opa_input
      required: false
      datatype: boolean
      default: false
      description: |
        If set to true, the current requests' request body is included as input to OPA.
    - name: include_parsed_json_body_in_opa_input
      required: false
      datatype: boolean
      default: false
      description: |
        If set to true and the `Content-Type` header of the current request is `application/json`, the request body will be JSON decoded and the decoded struct is included as input to OPA.
    - name: include_uri_captures_in_opa_input
      required: false
      datatype: boolean
      default: false
      minimum_version: "3.0.x"
      description: |
        If set to true, the [regex capture groups](https://docs.konghq.com/gateway/latest/reference/proxy/#using-regex-in-paths) captured on the Kong Gateway Route's path field in the current request (if any) are included as input to OPA.
    - name: ssl_verify
      required: true
      datatype: boolean
      default: true
      description: |
        If set to true, the OPA certificate will be verified according to the CA certificates specified in [lua_ssl_trusted_certificate](/gateway/latest/reference/configuration/#lua_ssl_trusted_certificate).
      minimum_version: "3.0.x"
