name: statsd-advanced
dbless_compatible: 'yes'
extra: |
  By default, the plugin sends a packet for each metric it observes. The `udp_packet_size` option
  configures the greatest datagram size the plugin can combine. It should be less than
  65507 according to UDP protocol. Please consider the MTU of the network when setting this parameter.

publisher: Kong Inc.
version: 2.2.x
desc: Send metrics to StatsD with more flexible options
description: |
  Log [metrics](#metrics) for a Service, route
  to a StatsD server.
  It can also be used to log metrics on [Collectd](https://collectd.org/)
  daemon by enabling its
  [StatsD plugin](https://collectd.org/wiki/index.php/Plugin:StatsD).

  The StatsD Advanced plugin provides
  features not available in the open-source [StatsD](/hub/kong-inc/statsd/) plugin, such as:
  * Ability to choose status codes to log to metrics.
  * More granular status codes per workspace.
  * Ability to use TCP instead of UDP.

categories:
  - analytics-monitoring
kong_version_compatibility:
  community_edition:
    compatible: null
  enterprise_edition:
    compatible:
    - 2.8.x
    - 2.7.x
    - 2.6.x
    - 2.5.x
    - 2.4.x
    - 2.3.x
    - 2.2.x
    - 2.1.x
    - 1.5.x
    - 1.3-x
    - 0.36-x
