name: Vault Authentication
dbless_compatible: 'yes'
manager_examples: false
konnect_examples: false

publisher: Kong Inc.
version: 2.1.x-2.7.x
desc: Add Vault authentication to your Services
description: |
  Add authentication to a Service or Route with an access token and secret token. Credential tokens are stored securely via Vault. Credential lifecyles can be managed through the Kong Admin API, or independently via Vault.

categories:
  - authentication
kong_version_compatibility:
  enterprise_edition:
    compatible: true
