name: Mocking
dbless_compatible: 'yes'
dbless_explanation: |
  {:.note}
  > Use the `api_specification` config for DB-less or hybrid mode. Attach the spec contents directly
  instead of uploading to the Dev Portal. The API spec is configured directly in the plugin.
examples: true
extra: |
  Depending on the Kong Gateway deployment mode, set either the `api_specification_filename`
  or the `api_specification` parameter. The plugin requires a spec to work.
free: No
plus: Yes
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - traffic-control
