#!/usr/bin/env bash

set -e

if [[ -v LOCALE && -v TRANSLATED_CONTENT_PATH && -v CONFIG_FILES ]]; then
    echo "Building site in $LOCALE..."
    bundle exec jekyll build --config jekyll.yml${CONFIG_FILES:+,$CONFIG_FILES} --profile
else
    echo "Building site in english..."
    bundle exec jekyll build --config jekyll.yml --profile
fi
