name: AppDynamics
bundled: false
konnect_examples: false
dbless_compatible: 'yes'
free: No
plus: No
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - analytics-monitoring
