name: Prometheus
dbless_compatible: 'yes'
dbless_explanation: |
  The database will always be reported as reachable in Prometheus with DB-less.
  Additionally, the DB entity count metric (`kong_db_entities_total`) is not
  emitted in DB-less mode.
free: true
enterprise: true
konnect: true
cloud_gateways: false
serverless_gateways: false
network_config_opts: traditional, hybrid, konnect hybrid, and db-less
notes: | 
   <b>Dedicated and Serverless Cloud Gateways</b>: This plugin is not supported in Dedicated or 
   Serverless Cloud Gateways because it depends on the Admin API and the Status API, which aren't 
   accessible in that setup.
categories:
  - analytics-monitoring
publisher: Kong Inc.
desc: Expose metrics related to Kong and proxied upstream services in Prometheus exposition format