name: Bot Detection
dbless_compatible: 'yes'
free: true
plus: true
enterprise: true
konnect: true
network_config_opts: All
notes: --
categories:
  - security
kong_version_compatibility:
  community_edition:
    compatible: true
  enterprise_edition:
    compatible: true
publisher: Kong Inc.
desc: Detect and block bots or custom clients
description: |
  Protects a Service or a Route from most common bots and has the capability of allowing and denying custom clients.
