name: bot-detection
service_id: true
route_id: true
consumer_id: false
protocols:
  - name: http
  - name: https
  - name: grpc
  - name: grpcs
dbless_compatible: 'yes'
config:
# deprecated parameters
  - name: whitelist
    required: false
    default:
    description: |
      A comma separated array of regular expressions that should be whitelisted. The regular expressions will be checked against the `User-Agent` header.
    maximum_version: "2.0.x"
  - name: blacklist
    required: false
    default:
    description: |
      A comma separated array of regular expressions that should be blacklisted. The regular expressions will be checked against the `User-Agent` header.
    maximum_version: "2.0.x"

# current parameters
  - name: allow
    required: false
    default: null
    datatype: array of string elements
    description: |
      An array of regular expressions that should be allowed. The regular expressions will be checked against the `User-Agent` header.
    minimum_version: "2.1.x"
  - name: deny
    required: false
    default: null
    datatype: array of string elements
    description: |
      An array of regular expressions that should be denied. The regular expressions will be checked against the `User-Agent` header.
    minimum_version: "2.1.x"
