name: Basic Authentication
dbless_compatible: partially
dbless_explanation: |
  Consumers and Credentials can be created with declarative configuration.

  Admin API endpoints which do POST, PUT, PATCH or DELETE on Credentials are not available on DB-less mode.

free: true
plus: true
enterprise: true
konnect: true
network_config_opts: All
notes: --
categories:
  - authentication
kong_version_compatibility:
  community_edition:
    compatible: true
  enterprise_edition:
    compatible: true
publisher: Kong Inc.
desc: Add Basic Authentication to your Services
description: |
  Add Basic Authentication to a Service or a Route with username and password protection. The plugin
  checks for valid credentials in the `Proxy-Authorization` and `Authorization` headers (in that order).
