name: Basic Authentication
dbless_compatible: partially
dbless_explanation: |
  Consumers and Credentials can be created with declarative configuration.

  Admin API endpoints which do POST, PUT, PATCH or DELETE on Credentials are not available on DB-less mode.

free: Yes
plus: Yes
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - authentication
