name: Request Termination
dbless_compatible: 'yes'
extra: |
  Once applied, every request (within the configured plugin scope of a Service,
  Route, Consumer, or global) will be immediately terminated by
  sending the configured response.
free: Yes
plus: Yes
enterprise: Yes
konnect: Yes
network_config_opts: All
notes: --
categories:
  - traffic-control
