name: Datadog
konnect_examples: false
dbless_compatible: 'yes'
free: true
plus: true
enterprise: true
konnect: true
network_config_opts: All
notes: --
categories:
  - analytics-monitoring
kong_version_compatibility:
  community_edition:
    compatible: true
  enterprise_edition:
    compatible: true
publisher: Kong Inc.
desc: Visualize metrics on Datadog
description: |
  Log [metrics](#metrics) for a service or route to a local
  [Datadog agent](http://docs.datadoghq.com/guides/basic_agent_usage/).
