name: Add plugin version
on:
  workflow_dispatch:
    inputs:
      type:
        description: "Edition to update"
        type: choice
        options:
          - community_edition
          - enterprise_edition
        required: true
      version:
        description: "Version to add"
        required: true
jobs:
  add-version:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      # Configure Node
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      # Add the versions
      - name: Add latest release version for "${{ github.event.inputs.type }}"
        env:
          RELEASE_TYPE: "${{ github.event.inputs.type }}"
          VERSION_TO_ADD: "${{ github.event.inputs.version }}"
        run: |
          cd build-scripts
          npm ci
          node add-latest-plugin-version.js
      # Raise PR with the updated changes
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Add version "${{ github.event.inputs.version }}" to "${{ github.event.inputs.type }}" plugins
          branch: automated-update-plugin-versions
          delete-branch: true
          title: "[Automated] Plugin version updates"
          body: |
            Automatic update with new plugin release
          labels: review:autodoc
