name: Update Konnect Changelog

on: workflow_dispatch

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Run changelog script
        working-directory: tools/beamer
        env:
          BEAMER_API_KEY: ${{ secrets.BEAMER_API_KEY }}
        run: |
          npm ci
          node fetch-beamer-posts.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Automated Konnect changelog update [skip-ci]
          body: |
            Latest Konnect changelog entries from beamer
          labels: skip-changelog,review:general
          base: main
          branch: automated-konnect-changelog-update
          token: ${{ secrets.PAT }}
          committer: kong-docs[bot] <team-docs@konghq.com>
          author: kong-docs[bot] <team-docs@konghq.com>
          delete-branch: true
          commit-message: "Automated Konnect changelog update"
