name: Install Instructions
on:
  workflow_dispatch:
    inputs:
      base_url:
        type: string
        description: URL to test against. Defaults to https://docs.konghq.com. Use the netlify preview URL when testing against a branch.

jobs:
  install-instructions:
    env:
      BASE_URL: https://docs.konghq.com
    strategy:
      fail-fast: false
      matrix:
        distro: [ubuntu, rhel, amazon-linux, debian, centos]
        arch: ["linux/amd64", "linux/arm64"]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: "recursive"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3
        with:
          platforms: arm64

      - name: Run Install tests
        env:
          DISTRO: ${{ matrix.distro }}
          ARCH: ${{ matrix.arch }}
          CONTINUE_ON_ERROR: 1
          IGNORE_SKIPS: 1
          EXPECTED_FAILURES_EXIT_CODE: 0
          BASE_URL: ${{ github.event.inputs.base_url || env.BASE_URL }}
        run: |
          cd tools/install-tester
          npm ci
          node index.js
