name: Push OAS Downstream
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  raise-pr-on-change:
    if: github.event.pull_request.merged == true
    name: Raise PR on change
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
          
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Raise PR on change
        uses: mheap/raise-pr-on-change-action@5bd79260e28f25d145f61a00cc3834c98069a30c # v1
        with:
           token: ${{ secrets.PAT }}
           configFile: ".github/raise-pr-on-change.json"
           prBranch: automated-update
           targetBranch: main
           prTitle: "feat(sdk): automated oas update - from docs repo"
           prBody: "Generated OAS files from docs.konghq.com"
           commitMessage: "feat(sdk): automated oas update from docs.konghq.com"
