# The repo sync workflow triggers a weekly Github Action that keeps the two
# Kong docs repos in sync:
# docs.konghq.com (public) and docs.konghq.com-private (...private).
#
# During times of heavy feature/doc development in the private repo, any repo
# admin can either manually trigger the action, or temporarily change the
# schedule to sync more often.
#
# Automated PRs are opened in the private repo only.
#
# This workflow is based on GitHub's implementation.
# For more details, see https://github.com/repo-sync/repo-sync#how-it-works

name: Repo Sync

on:
  workflow_dispatch: 
  schedule:
  - cron: "0 0 * * *" # once every day
  

jobs:
  repo-sync:
    if: github.repository == 'kong/docs.konghq.com-private'
    name: Repo Sync
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Sync repository to branch
      uses: repo-sync/github-sync@v2
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SYNC_TOKEN }}
      with:
        source_repo: ${{ secrets.SOURCE_REPO }}
        source_branch: main
        destination_branch: chore/repo-sync
        github_token: ${{ secrets.REPO_SYNC_TOKEN }}

    - name: Create pull request
      uses: repo-sync/pull-request@v2
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SYNC_TOKEN }}
      with:
        source_branch: chore/repo-sync
        destination_branch: main
        github_token: ${{ secrets.REPO_SYNC_TOKEN }}
        pr_title: "(chore) Sync public to private"
        pr_body: "Automated PR for syncing the `main` branches of the Kong docs repos. When merging, choose the option to **Merge pull request** on the big green button (click the dropdown arrow and choose **Create a merge commit** if you don't see it); **do not squash**!"
        pr_label: automated-pr

    - name: Find pull request
      uses: juliangruber/find-pull-request-action@v1
      id: find-pull-request
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: chore/repo-sync
        base: main

    - name: Approve pull request
      if: ${{ steps.find-pull-request.outputs.number }}
      uses: juliangruber/approve-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: ${{ steps.find-pull-request.outputs.number }}
