name: Upload Plugins for translation
on:
  workflow_dispatch:
    inputs:
      versions:
        type: string
        description: |
          Comma-separated list of gateway versions to translate.
          If not provided, the config file in tools/smartling-integration/config.yml will be used.
      locale:
        type: string
        default: 'ja-JP'
        description: "Target locale, it must match the same format that the Job has, e.g. `ja-JP`."
      jobId:
        type: string
        description: "Smarting's JobUId in case we want to re-upload some files to an existing Job"

jobs:
  upload-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: |
          cd tools/smartling-integration
          npm ci
      - name: Run upload tool
        run: |
          node tools/smartling-integration/upload_plugins.js
        env:
          PROJECT_ID: ${{ secrets.SMARTLING_PROJECT_ID }}
          USER_IDENTIFIER: ${{ secrets.SMARTLING_USER_IDENTIFIER }}
          USER_SECRET: ${{ secrets.SMARTLING_USER_SECRET }}
          JOB_ID: ${{ github.event.inputs.jobId }}
          LOCALE: ${{ github.event.inputs.locale }}
          VERSIONS: ${{ github.event.inputs.versions }}
