extends: substitution
message: Use '%s' instead of '%s'.
level: error
ignorecase: false
swap:
  kong: Kong
  k8s: Kubernetes
  Kong Gateway: "{{site.base_gateway}}"
  Konnect: "{{site.konnect_short_name}}"
  Konnect Cloud: "{{site.konnect_saas}}"
  pg: PostgreSQL
  'postgres$': PostgreSQL
  hashicorp: HashiCorp
  blacklist: denylist
  whitelist: allowlist
  dbless: "DB-less"
  codeblock: "code block"
