extends: substitution
message: Use '%s' instead of '%s'.
level: error
ignorecase: true
swap:

  datacenter: data center
  codeblock': code block
  blacklist: denylist
  codeblock: code block
  dbless: DB-less
  file name: filename
  # '(?:kubernetes|k8s)': Kubernetes
  kong gateway: "{{site.base_gateway}}"
  Konnect Cloud: "{{site.konnect_saas}}"
  multizone: multi-zone
  pg: PostgreSQL
  'postgres$': PostgreSQL
  'self(?:-| )hosted': self-managed
  redhat: Red Hat
  ServiceHub: Service Hub
  timezone: time zone
  utilize: use
  whitelist: allowlist

