extends: substitution
message: Use '%s' instead of '%s'.
level: error
ignorecase: true
swap:
  kong: Kong
  k8s: Kubernetes
  Kong Gateway: "{{site.base_gateway}}"
  konnect: "{{site.konnect_short_name}}"
  Konnect Cloud: "{{site.konnect_saas}}"
  kuma: Kuma
  grafana: Grafana
  postgres: PostgreSQL
  hashicorp: HashiCorp