extends: substitution
message: Use '%s' instead of '%s'.
level: error
ignorecase: false
swap:
  blacklist: denylist
  codeblock: code block
  dbless: DB-less
  file name: filename
  hashicorp: HashiCorp
  kong: Kong
  k8s: Kubernetes
  Kong Gateway: "{{site.base_gateway}}"
  Konnect: "{{site.konnect_short_name}}"
  Konnect Cloud: "{{site.konnect_saas}}"
  pg: PostgreSQL
  'postgres$': PostgreSQL
  self hosted: self-managed
  self-hosted: self-managed
  ServiceHub: Service Hub
  timezone: time zone
  utilize: use
  whitelist: allowlist
