ja:
  gateway:
    - 3.6.x
    - 3.5.x
    - 3.4.x
  kgo:
    - 1.2.x
    - 1.1.x
  kic:
    - 3.0.x
    - 2.9.x
  konnect: []

  plugins:
    kong-inc:
      - key-auth
      - cors
      - rate-limiting
      - acl
      - basic-auth
      - openid-connect
      - request-transformer
      - jwt
      - proxy-cache
      - prometheus
